routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'TestController@welcome');

/*Route::get('/prueba',function(){
	return 'Hola soy la ruta prueba';
});*/
Auth::routes();

/**Busqueda de Productos */
Route::get('/search','SearchController@show');
Route::get('/products/json','SearchController@data');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/products/{product}','ProductController@show')->name('product.show'); //Mostrar Informacion de de Los Productos
Route::get('/categories/{category}','CategoryController@show');

/**Para Agregar Productos al Carrito*/
Route::post('/cart','CartDetailController@store');
/**Para Eliminar Productos al Carrito*/
Route::delete('/cart','CartDetailController@destroy');
/**Para Realizar el Pedido de los Productos del Carrito*/
Route::post('/order','CartController@update');

Route::middleware(['auth','admin'])->prefix('admin')->namespace('Admin')->group(function () {
		Route::get('/products','ProductController@index'); //Listados de Los Productos
		Route::get('/products/create','ProductController@create'); //Formulario de Alta de Los Productos
		Route::post('/products','ProductController@store'); //Guardar el Alta de Los Productos
		Route::get('/products/{id}/edit','ProductController@edit'); //Formulario de Edicion de Los Productos
		Route::post('/products/{id}/edit','ProductController@update'); //Guardar la Edicion de Los Productos
		Route::delete('/products/{id}','ProductController@destroy'); //Formulario para Eliminar Los Productos

		Route::get('/products/{id}/images','ImageController@index'); //Listados de las Imagenes de Los Productos y formulario de edicion
		Route::post('/products/{id}/images','ImageController@store'); //Guarda las Imagenes de Los Productos
		Route::delete('/products/{id}/images','ImageController@destroy'); //Elimina las Imagenes de Los Productos
        Route::get('/products/{id}/images/select/{image}','ImageController@select'); //Destacar Imagenes de Los Productos

        /**Rutas Para Administrar las Categorias */
        Route::get('/categories','CategoryController@index'); //Listados de Los Categorias
		Route::get('/categories/create','CategoryController@create'); //Formulario de Alta de Los Categorias
		Route::post('/categories','CategoryController@store'); //Guardar el Alta de Los Categorias
		Route::get('/categories/{category}/edit','CategoryController@edit'); //Formulario de Edicion de Los Categorias
		Route::post('/categories/{category}/edit','CategoryController@update'); //Guardar la Edicion de Los Categorias
		Route::delete('/categories/{category}','CategoryController@destroy'); //Formulario para Eliminar Los Categorias
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

 /**Línea necesaria para Borrado Logico*/
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes; //Implementamos

    /**Registramos la nueva columna */
    protected $dates = ['deleted_at'];

    // $products->category
    public function category()
    {
    	return $this->belongsTo(Category::class);
    }
    // $products->provider
    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }
    // $products->images
    public function images()
    {
    	return $this->hasMany(ProductImage::class);
    }
    public function getFeaturedImageUrlAttribute()
    {
        $featuredImage = $this->images()->where('featured', true)->first();
        if (!$featuredImage)
        {
            $featuredImage = $this->images()->first();
        }
          if ($featuredImage) {
            return $featuredImage->url;
        }
        //default
        return '/images/products/default.png';
    }
  public function getCategoryNameAttribute()
  {
    if ($this->category) {
      return $this->category->name;
    }
    return 'General';
  }
  public function getProviderNameAttribute()
  {
    if ($this->provider) {
      return $this->provider->name;
    }
    return 'Sin Proveedor';
  }
}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Product;

class SearchController extends Controller
{
    public function show(Request $request)
    {
        $query = $request->input('query');
        $products = Product::where('name', 'like', "%$query%")->paginate(10);
        /**Vemos si la Coincidencia es un Producto es decir exacta le llevamos al producto */
        if ($products->count() == 1) {
            $id = $products->first()->id;
            return redirect("products/$id");// 'products/'.$id
        }
        return view('search.show')->with(compact('products', 'query'));
    }
    public function data()
    {
        $products = Product::pluck('name');//Devuelve un arreglo con todos los nombres de los productos
        return $products;
    }
}

resources/views/search/show.blade.php
@extends('layouts.app')

@section('title','Resultados de Búsqueda Pequitas Lenceria')

@section('style')
    <style>
        .team {
            padding-bottom: 50px;
        }
    </style>
@endsection

@section('body-class','profile-page sidebar-collapse')

@section('content')
<div class="page-header header-filter" data-parallax="true" style="background-image: url('{{ asset('img/city-profile.jpg') }}');"></div>

<div class="main main-raised">
    <div class="profile-content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile">
              <div class="avatar">
                <img src="/img/search.png" alt="Imagen de Busqueda" class="img-raised rounded-circle img-fluid">
              </div>
              <div class="name">
                <h3 class="title">Resultados de Búsqueda</h3>
                @include('flash::message')
              </div>
            </div>
          </div>
        </div>
        <div class="description text-center">
          <p>Se Encontraron {{$products->count()}} con el Término {{$query}}.</p>
        </div>
        <div class="team text-center">
            <div class="row">
              @foreach ($products as $product)
              <div class="col-md-4">
                <div class="team-player">
                  <div class="card card-plain">
                    <div class="col-md-6 ml-auto mr-auto">
                      <img src="{{ $product->featured_image_url }}" alt="Thumbnail Image" class="img-raised rounded-circle img-fluid">
                    </div>
                    <h4 class="card-title">
                      <a href="{{ url('/products/'.$product->id)}}">{{ $product->name }}</a>
                    </h4>
                    <div class="card-body">
                      <p class="card-description">{{ $product->description }}</p>
                    </div>
                  </div>
                </div>
              </div>
              @endforeach
            </div>
            <nav class="justify-content-center">
              {{ $products->links()}}
             </nav>
          </div>
        </div>

    </div>

  </div>
 </div>
@include('includes.footer');
@endsection