routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'TestController@welcome');

/*Route::get('/prueba',function(){
	return 'Hola soy la ruta prueba';
});*/
Auth::routes();

/**Busqueda de Productos */
Route::get('/search','SearchController@show');
Route::get('/products/json','SearchController@data');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/products/{product}','ProductController@show')->name('product.show'); //Mostrar Informacion de de Los Productos
Route::get('/categories/{category}','CategoryController@show');

/**Para Agregar Productos al Carrito*/
Route::post('/cart','CartDetailController@store');
/**Para Eliminar Productos al Carrito*/
Route::delete('/cart','CartDetailController@destroy');
/**Para Realizar el Pedido de los Productos del Carrito*/
Route::post('/order','CartController@update');

Route::middleware(['auth','admin'])->prefix('admin')->namespace('Admin')->group(function () {
		Route::get('/products','ProductController@index'); //Listados de Los Productos
		Route::get('/products/create','ProductController@create'); //Formulario de Alta de Los Productos
		Route::post('/products','ProductController@store'); //Guardar el Alta de Los Productos
		Route::get('/products/{id}/edit','ProductController@edit'); //Formulario de Edicion de Los Productos
		Route::post('/products/{id}/edit','ProductController@update'); //Guardar la Edicion de Los Productos
		Route::delete('/products/{id}','ProductController@destroy'); //Formulario para Eliminar Los Productos

		Route::get('/products/{id}/images','ImageController@index'); //Listados de las Imagenes de Los Productos y formulario de edicion
		Route::post('/products/{id}/images','ImageController@store'); //Guarda las Imagenes de Los Productos
		Route::delete('/products/{id}/images','ImageController@destroy'); //Elimina las Imagenes de Los Productos
        Route::get('/products/{id}/images/select/{image}','ImageController@select'); //Destacar Imagenes de Los Productos

        /**Rutas Para Administrar las Categorias */
        Route::get('/categories','CategoryController@index'); //Listados de Los Categorias
		Route::get('/categories/create','CategoryController@create'); //Formulario de Alta de Los Categorias
		Route::post('/categories','CategoryController@store'); //Guardar el Alta de Los Categorias
		Route::get('/categories/{category}/edit','CategoryController@edit'); //Formulario de Edicion de Los Categorias
		Route::post('/categories/{category}/edit','CategoryController@update'); //Guardar la Edicion de Los Categorias
		Route::delete('/categories/{category}','CategoryController@destroy'); //Formulario para Eliminar Los Categorias
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

 /**Línea necesaria para Borrado Logico*/
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes; //Implementamos

    /**Registramos la nueva columna */
    protected $dates = ['deleted_at'];

    // $products->category
    public function category()
    {
    	return $this->belongsTo(Category::class);
    }
    // $products->provider
    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }
    // $products->images
    public function images()
    {
    	return $this->hasMany(ProductImage::class);
    }
    public function getFeaturedImageUrlAttribute()
    {
        $featuredImage = $this->images()->where('featured', true)->first();
        if (!$featuredImage)
        {
            $featuredImage = $this->images()->first();
        }
          if ($featuredImage) {
            return $featuredImage->url;
        }
        //default
        return '/images/products/default.png';
    }
  public function getCategoryNameAttribute()
  {
    if ($this->category) {
      return $this->category->name;
    }
    return 'General';
  }
  public function getProviderNameAttribute()
  {
    if ($this->provider) {
      return $this->provider->name;
    }
    return 'Sin Proveedor';
  }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

use App\Product;
use App\Category;
use App\Provider;
use App\ProductImage;
use App\Colour;
use App\Waist;

class ProductController extends Controller
{

    public function index()
    {
    	$products = Product::paginate(10);
    	return view('admin.products.index')->with(compact('products')); //Listado de los Productos
    }
        public function create()
    {
    	$categories = Category::orderBy('name')->get();
        $providers = Provider::orderBy('name')->get();
        $colours = Colour::orderBy('name')->get();
        $waists = Waist::orderBy('name')->get();
    	return view('admin.products.create')->with(compact('categories','providers','colours','waists')); //Formulario de Alta de los Productos
    }
        public function store(Request $request)
    {
    	//Guardar el Alta de Los Productos
    	//dd($request->all());
    	//Validaciones y mensajes personalizados

		$messages = [
			'name.required' => 'Es necesario ingresar un Cod. de Producto.',
			'name.min'      => 'El codigo de producto debe tener al menos 3 caracteres.',
			'description.required' => 'Es necesario ingresar una descripcion corta.',
			'description.max' => 'La descripción corta solo admite hasta 200 caracteres.',
			'waist.required' => 'Es necesario ingresar los Talles Disponibles.',
			'waist.max' => 'Los Talles Disponibles solo admite hasta 200 caracteres.',
			'colour.required' => 'Es necesario ingresar los Colores Disponibles.',
			'colour.max' => 'Los Colores Disponibles solo admite hasta 200 caracteres.',
			'price.required'  => 'Es necesario definir un precio al producto.',
			'price.numeric'   => 'Ingrese un precio valido.',
			'price.min'       => 'No se admiten valores negativos.',
			'cost_price.required'  => 'Es necesario definir un precio de costo al producto.',
			'cost_price.numeric'   => 'Ingrese un precio valido.',
			'cost_price.min'       => 'No se admiten valores negativos.',
			'providers.required' => 'Es necesario selecionar un Proveedor.',
			'category_id.required' => 'Es necesario selecionar una Marca.'
		];

		$rules = [
			'name' => 'required|min:3',
			'description' => 'required|max:200',
			'waist' => 'required|max:200',
			'colour' => 'required|max:200',
			'price' => 'required|numeric|min:0' ,//No negativos
			'cost_price' => 'required|numeric|min:0', //No negativos
			'providers' => 'required',
			'category_id' => 'required'
		];

		$this->validate($request, $rules, $messages);

    	//Instanciamos
    	$product = new Product();
    	//Recibimos los datos
    	$product->name = $request->input('name');
    	$product->price = $request->input('price');

        /*=============================================
        =  RECIBIMOS LOS COLORES Y LO CONCATENAMOS    =
        =============================================*/
        $colours="";
        foreach ($request->input('colour') as $colour) {
            $colours .= $colour.'; ';
        }
        //INSERTAMOS LOS COLORES Y LIMPIAMOS EL ULTIMO CARACTER
         $product->colours =rtrim($colours,'; ') ;
        /*===== FIN RECIBIMOS LOS COLORES Y LO CONCATENAMOS   ======*/

        /*=============================================
        =  RECIBIMOS LOS TALLES Y LO CONCATENAMOS    =
        =============================================*/
        $waists="";
        foreach ($request->input('waist') as $waist) {
            $waists .= $waist.'; ';
        }
        //INSERTAMOS LOS TALLES Y LIMPIAMOS EL ULTIMO CARACTER
        $product->waists = rtrim($waists,'; ');
    	/*===== FIN RECIBIMOS LOS TALLES Y LO CONCATENAMOS   ======*/

    	$product->description = $request->input('description');
    	$product->long_description = $request->input('long_description');
    	$product->cost_price = $request->input('cost_price');
    	$product->provider_id = $request->input('providers');
    	$product->category_id = $request->input('category_id');;

    	$product->save();//Insertamos los Datos en la Base
        /**Generamos un Mensaje */
        flash('¡Bien Hecho! Se Agrego Correctamente el Producto.')->success()->important();
    	return redirect('admin/products/');
    }
 		public function edit($id)
    {
    	$product = Product::find($id);
    	$categories = Category::orderBy('name')->get();
        $providers = Provider::orderBy('name')->get();
        $colours = Colour::orderBy('name')->get();
        $waists = Waist::orderBy('name')->get();
    	return view('admin.products.edit')->with(compact('product','categories','providers','colours','waists')); //Formulario de Edicion de los Productos
    }

        public function update(Request $request, $id)
    {
    	//Buscamos el Producto

        $product = Product::find($id);

    	//Validaciones y mensajes personalizados

		$messages = [
			'name.required' => 'Es necesario ingresar un Cod. de Producto.',
			'name.min'      => 'El codigo de producto debe tener al menos 3 caracteres.',
			'description.required' => 'Es necesario ingresar una descripcion corta.',
			'description.max' => 'La descripción corta solo admite hasta 200 caracteres.',
			'waist.required' => 'Es necesario ingresar los Talles Disponibles.',
			'waist.max' => 'Los Talles Disponibles solo admite hasta 200 caracteres.',
			'colour.required' => 'Es necesario ingresar los Colores Disponibles.',
			'colour.max' => 'Los Colores Disponibles solo admite hasta 200 caracteres.',
			'price.required'  => 'Es necesario definir un precio al producto.',
			'price.numeric'   => 'Ingrese un precio valido.',
			'price.min'       => 'No se admiten valores negativos.',
			'cost_price.required'  => 'Es necesario definir un precio de costo al producto.',
			'cost_price.numeric'   => 'Ingrese un precio valido.',
			'cost_price.min'       => 'No se admiten valores negativos.',
			'providers.required' => 'Es necesario selecionar un Proveedor.',
			'category_id.required' => 'Es necesario selecionar una Marca.'
		];

		$rules = [
			'name' => 'required|min:3',
			'description' => 'required|max:200',
			'waist' => 'required|max:200',
			'colour' => 'required|max:200',
			'price' => 'required|numeric|min:0' ,//No negativos
			'cost_price' => 'required|numeric|min:0', //No negativos
			'providers' => 'required',
			'category_id' => 'required'
		];

		$this->validate($request, $rules, $messages);

    	//Recibimos los datos
    	$product->name = $request->input('name');
    	$product->price = $request->input('price');

        /*=============================================
        =  RECIBIMOS LOS COLORES Y LO CONCATENAMOS    =
        =============================================*/
        $colours="";
        foreach ($request->input('colour') as $colour) {
            $colours .= $colour.'; ';
        }
        //INSERTAMOS LOS COLORES Y LIMPIAMOS EL ULTIMO CARACTER
         $product->colours =rtrim($colours,'; ') ;
        /*===== FIN RECIBIMOS LOS COLORES Y LO CONCATENAMOS   ======*/

        /*=============================================
        =  RECIBIMOS LOS TALLES Y LO CONCATENAMOS    =
        =============================================*/
        $waists="";
        foreach ($request->input('waist') as $waist) {
            $waists .= $waist.'; ';
        }
        //INSERTAMOS LOS TALLES Y LIMPIAMOS EL ULTIMO CARACTER
        $product->waists = rtrim($waists,'; ');
        /*===== FIN RECIBIMOS LOS TALLES Y LO CONCATENAMOS   ======*/

    	$product->description = $request->input('description');
    	$product->long_description = $request->input('long_description');
    	$product->cost_price = $request->input('cost_price');
    	$product->provider_id = $request->input('providers');
    	$product->category_id = $request->input('category_id');

    	$product->save();//Actualizamos los Datos en la Base
        /**Generamos un Mensaje */
        flash('¡Bien Hecho! Se Edito Correctamente el Producto.')->success()->important();
    	return redirect('admin/products/');
    }
        public function destroy($id)
    {
    	//Buscamos el Producto
    	$product = Product::find($id);
    	$product->delete();//Eliminamos los Datos en la Base
        /**Generamos un Mensaje */
        flash('¡Bien Hecho! Se Elimino Correctamente el Producto.')->success()->important();
    	return back();
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;

use Illuminate\Http\Request;

class ProductController extends Controller
{
     public function show(Product $product)
    {
       	$images = $product->images;
      
      // Repartir las imágenes al lado izquierdo y derecho
    	$imagesLeft  = collect();
    	$imagesRight = collect();
      foreach ($images as $key => $image)
      {
    		if ($key%2 == 0) {
    			$imagesLeft->push($image);
        }	else {
    			$imagesRight->push($image);
        }
    	}
      
    	return view('products.show')->with(compact('product', 'imagesLeft', 'imagesRight'));
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('title','Agregar Productos Pequitas Lenceria')

@section('body-class','profile-page sidebar-collapse')

@section('content')
<div class="page-header header-filter" data-parallax="true" style="background-image: url('{{ asset('img/profile_city.jpg')}}')">
</div>
  <div class="main main-raised">
  <div class="container">
    <div class="section text-center">
      <h3 class="title">Agregar Productos</h2>
      @if ($errors->any())
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button  type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <ul>
              @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
        @endif
      <div class="team">
        <form method="post" action="{{ url('/admin/products')}}">
            @csrf
          <div class="row">
            <div class="col-sm-6">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fa fa-barcode"></i>
                  </span>
                </div>
                <input id="name" name="name" type="text" class="form-control" placeholder="Cod. de Producto" value="{{ old('name') }}">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fa fa-usd"></i>
                  </span>
                </div>
                <input id="price" name="price" step="0.01" type="number" class="form-control" placeholder="Precio de Venta del Producto" value="{{ old('price') }}">
              </div>
            </div>
            </div>
               </br>
            <div class="row">
            <div class="col-sm-6">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fa fa-align-justify"></i>
                  </span>
                </div>
                <select class="form-control selectpicker" data-style="btn btn-round btn-primary select-with-transition" multiple data-live-search="true" name="waist[]" data-size="6" title="Seleccione los Talles Disponibles">
                @foreach ($waists as $waist)
                  <option data-tokens="{{ $waist->name}}"
                  @if (old('waist')){{ (in_array($waist->name, old('waist')) ? 'selected':'') }}@endif value="{{ $waist->name}}">{{ $waist->name}}</option>
                @endforeach
                 </select>
                <!-- <input id="waists" name="waists" type="text" class="form-control" placeholder="Talles Disponibles" value="{{ old('waists') }}"> -->
              </div>
            </div>
            <div class="col-sm-6">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fa fa-paint-brush"></i>
                  </span>
                </div>
             <select class="form-control selectpicker" data-style="btn btn-round btn-primary select-with-transition" multiple data-live-search="true" name="colour[]" data-size="6" title="Seleccione los Colores Disponibles">
                @foreach ($colours as $colour)
                <option data-tokens="{{ $colour->name}}"
                @if (old('colour')){{ (in_array($colour->name, old('colour')) ? 'selected':'') }}@endif value="{{ $colour->name}}">{{ $colour->name}}</option>
                @endforeach
                </select>
                <!--   <input id="colours" name="colours" type="text" class="form-control" placeholder="Colores Disponibles" value="{{ old('colours') }}">-->
              </div>
            </div>
            </div>
               </br>
            <div class="row">
            <div class="col-sm-6">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fa fa-file-text"></i>
                  </span>
                </div>
                <input id="description" name="description" type="text" class="form-control" placeholder="Descripción Corta" value="{{ old('description') }}">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                   <i class="fa fa-registered" aria-hidden="true"></i>
                  </span>
                </div>
              <select id="category_id" name="category_id" class="form-control">
                <option selected disabled="true">Elija una Marca</option>
                @foreach ($categories as $category)
                <option value="{{$category->id}}" @if($category->id == old('category_id')) selected @endif>{{ $category->name}}</option>
                @endforeach
                </select>
              </div>
            </div>
          </div>
             </br>
          <div class="row">
            <div class="col-sm-6">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fa fa-usd"></i>
                  </span>
                </div>
                <input id="cost_price" name="cost_price" step="0.01" type="number" class="form-control" placeholder="Precio de costo del Producto" value="{{ old('cost_price') }}">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fa fa-shopping-bag"></i>
                  </span>
                </div>
                <select id="providers" name="providers" class="form-control">
                <option selected disabled="true">Elija un Proveedor</option>
                @foreach ($providers as $provider)
                <option @if($provider->name == old('providers')) selected @endif value="{{$provider->id}}">{{$provider->name}}</option>
                @endforeach
                </select>
                <!-- <input id="providers" name="providers" type="text" class="form-control" placeholder="Proveedores" value="{{ old('providers') }}"> -->
              </div>
            </div>
            </div>
            <div class="row">
            <div class="col-sm-8">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">
                    <i class="fa fa-file-text"></i>
                  </span>
                </div>
                <textarea id="long_description" name="long_description" class="form-control" placeholder="Descripción Larga" rows="4">{{ old('long_description') }}</textarea>
              </div>
            </div>
            </div>
          </br>
            <button type="submit" class="btn btn-round btn-rose">Gurdar Producto</button>
            <a href="{{ url('/admin/products')}}" class="btn btn-primary btn-round">Cancelar</a>
        </form>
      </div>
    </div>
</div>

</div>
@include('includes.footer');
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('title','Listado de Productos Pequitas Lenceria')

@section('body-class','profile-page sidebar-collapse')

@section('content')
<div class="page-header header-filter" data-parallax="true" style="background-image: url('{{ asset('img/profile_city.jpg')}}')">
</div>

  <div class="main main-raised">

  <div class="container">
    <div class="section text-center">
      <h3 class="title">Listado de Productos Disponibles</h3>
      @include('flash::message')
      <div class="team">
        <div class="row table-responsive">
          <a href="{{ url('/admin/products/create') }}" class="btn btn-primary btn-round btn-rose">Agregar Producto</a>
            <table class="table table-bordered table-hover table-sm">
              <thead class="table-danger">
                  <tr>
                      <th class="text-center">#</th>
                      <th class="text-center col-sm-1">Cod. Artículo</th>
                      <th class="text-center col-sm-2">Talles Disponibles</th>
                      <th class="text-center col-sm-2">Colores Disponibles</th>
                      <th class="text-center col-sm-2">Precio de Venta</th>
                      <th class="text-center col-sm-2">Precio de Costo</th>
                      <th class="text-center col-sm-1">Categoria</th>
                      <th class="text-center col-sm-1">Proveedor</th>
                      <th class="text-center col-sm-1">Opciones</th>
                  </tr>
              </thead>
              <tbody>
                @foreach ($products as $product)
                  <tr>
                      <td class="text-center">{{ $product->id }}</td>
                      <td>{{ $product->name }}</td>
                      <td>{{ $product->waists}}</td>
                      <td>{{ $product->colours}}</td>
                      <td class="text-center">&#36; {{ $product->price}}</td>
                      <td class="text-center">&#36; {{ $product->cost_price}}</td>
                      <td>{{ $product->category_name}}</td>
                      <td>{{ $product->provider_name}}</td>
                      <td class="td-actions text-center small">
                          <form method="post" action="{{ url('/admin/products/'.$product->id)}}">
                          <a href="{{ url('/products/'.$product->id) }}" target="_blank" data-toggle="tooltip" data-placement="top" title="Ver Producto" class="btn btn-info btn-fab btn-fab-mini btn-round">
                              <i class="material-icons">info</i>
                          </a>
                          <a href="{{ url('/admin/products/'.$product->id.'/edit')}}" data-toggle="tooltip" data-placement="top" title="Editar Producto" class="btn btn-success btn-fab btn-fab-mini btn-round">
                              <i class="material-icons">edit</i>
                          </a>
                          <a href="{{ url('/admin/products/'.$product->id.'/images')}}" data-toggle="tooltip" data-placement="top" title="Imagenes del Producto" class="btn btn-warning btn-fab btn-fab-mini btn-round">
                              <i class="material-icons">collections</i>
                          </a>
                           @csrf
                           @method('DELETE')
                          <button type="submit" data-toggle="tooltip" data-placement="top" title="Eliminar Producto" class="btn btn-danger btn-fab btn-fab-mini btn-round">
                              <i class="material-icons">close</i>
                          </button>
                          </form>
                      </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>
        </div>
       {{ $products->links()}}
      </div>
    </div>
</div>

</div>
@include('includes.footer');
@endsection